common:
  dataset_name: "steam" # "goodreads" "movielens1m"
  model_type: "tgqn" # "gcqn" "svdq" "rnnq" "random"
  model_info: ""
  optimizer: "Adam"
  scheduler: "ReduceLROnPlateau"
  device: "cpu"
  seed: 1488
  batch_size: 32
  test_size: 1000
  n_episodes: 200
  n_valid_episodes: 2
  annealing_num_steps: 400
  e_greedy_eps_init: 0.5
  updater_type: "soft" # "hard"
  soft_updater_eps: 0.95
  hard_updater_value_network_update_interval: 15
  optimizer_lr: 1e-4

tgqn:
  memory_dim: 100
  embedding_dim: 100
  reward_dim: 32
  num_heads: 4
  num_layers: 2
  num_neighbours: 10
  gnn_type: "edge_gat"
  rnn_type: "lstm"
  memory_alpha: 0.7
  use_users_raw_embeddings: True
  items_memory_batch_agg: "mean"
  items_embedding_module_input: "cat"
  users_embedding_module_input: "cat"
  predictor_type: "mlp"
  predictor_hidden_dim: 100
  users_predictor_input: "cat"
  items_predictor_input: "cat"
  use_items_memory_as_hidden: False
  pos_interactions_only: False
  dropout: 0.2

gcqn:
  raw_embedding_dim: 100
  gnn_embedding_dim: 100
  rnn_embedding_dim: 100
  reward_dim: 32
  num_heads: 4
  num_layers: 1
  num_neighbours: 10
  gnn_type: "gat"
  rnn_type: "gru"
  predictor_type: "mlp"
  use_rewards_in_rnn: True
  predictor_hidden_dim: 100

svdq:
  embedding_dim: 32

rnnq:
  embedding_dim: 64
  rnn_type: "gru"
  reward_dim: 16,
  use_rewards: True

random:
